import assert from 'node:assert/strict';
import {LockedTarget,selectionCandidates,describePose,contentRect} from '../site/target-lock.js';
let cases=0;const check=(name,fn)=>{fn();cases++;console.log('PASS',name);};
const pose=(x,y=.2)=>{const lm=Array.from({length:33},()=>({x,y,visibility:1,presence:1}));for(const [i,dx,dy] of [[11,-.025,0],[12,.025,0],[23,-.02,.12],[24,.02,.12],[25,-.02,.20],[26,.02,.20],[27,-.02,.30],[28,.02,.30],[29,-.02,.31],[30,.02,.31],[31,-.03,.32],[32,.03,.32]])lm[i]={x:x+dx,y:y+dy,visibility:1,presence:1};return lm;};
const shirt=bin=>({hist:Array.from({length:16},(_,i)=>Number(i===bin))});
const lock=(x=.4)=>new LockedTarget({id:'T-test',landmarks:pose(x),time:0,appearance:shirt(0),aspect:16/9});
check('click outside all boxes never snaps to nearest',()=>assert.deepEqual(selectionCandidates([pose(.2),pose(.8)],{kind:'point',point:{x:.5,y:.35}}),[]));
check('overlapping hit returns both instead of choosing a center',()=>assert.deepEqual(selectionCandidates([pose(.4),pose(.42)],{kind:'point',point:{x:.41,y:.25}}),[0,1]));
check('ROI requires torso inside explicit box',()=>assert.deepEqual(selectionCandidates([pose(.2),pose(.8)],{kind:'box',box:{x1:.75,y1:.18,x2:.85,y2:.55}}),[1]));
check('letterbox mapping excludes black bars',()=>assert.deepEqual(contentRect(400,400,1920,1080),{x:0,y:87.5,width:400,height:225}));
check('first snapshot is a value copy',()=>{const p=pose(.4),l=new LockedTarget({id:'T1',landmarks:p,time:0});p[25].x=.9;assert.notEqual(l.seedPose[25].x,p[25].x);});
check('missing target refuses distant bystander',()=>assert.equal(lock().match([pose(.8)],.033,[shirt(0)]).index,-1));
check('clothing anchor prevents replacement near old position',()=>assert.equal(lock().match([pose(.4)],.033,[shirt(6)]).state,'lost'));
check('ambiguity is latched, not silently reacquired',()=>{const l=lock();assert.equal(l.match([pose(.395),pose(.405)],.033,[shirt(0),shirt(0)]).state,'ambiguous');assert.equal(l.match([pose(.4)],.066,[shirt(0)]).index,-1);});
check('lost track stays stopped even if target returns',()=>{const l=lock();l.match([],.033);assert.equal(l.match([pose(.4)],.066,[shirt(0)]).index,-1);});
check('strong body overlap rejected despite different clothing',()=>assert.equal(lock().match([pose(.4),pose(.41)],.033,[shirt(0),shirt(6)]).state,'ambiguous'));
check('broken torso cannot become target',()=>{const p=pose(.4);for(const i of [11,12])p[i].visibility=0;assert.equal(describePose(p),null);});
check('temporal discontinuity requires reselection',()=>assert.equal(lock().match([pose(.4)],3,[shirt(0)]).index,-1));
const permutations=a=>a.length?a.flatMap((x,i)=>permutations(a.filter((_,j)=>i!==j)).map(p=>[x,...p])):[[]];
for(const order of permutations([0,1,2,3]))check('four-person order '+order.join(','),()=>{const xs=[.15,.35,.60,.85],chosen=2,l=new LockedTarget({id:'selected-third',landmarks:pose(xs[chosen]),time:0,appearance:shirt(0),aspect:16/9});for(let k=1;k<=30;k++){const people=order.map(i=>pose(xs[i]+k*.001)),r=l.match(people,k/30,order.map(()=>shirt(0)));assert.equal(order[r.index],chosen);assert.equal(r.targetId,'selected-third');}});
console.log(JSON.stringify({suite:'target-lock',cases,permutedFrameChecks:24*30,passed:true,scope:'synthetic association invariants, not video identity accuracy'}));
